# Generated by Django 3.1.4 on 2021-01-16 01:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='collabrator',
            field=models.ManyToManyField(blank=True, related_name='Collabrator_of_note', to=settings.AUTH_USER_MODEL),
        ),
    ]
