# Generated by Django 3.1.4 on 2021-01-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0002_notes_collabrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='trashed_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
